/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.factura;

import ec.edu.ups.controladores.ControladorFactura;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.FacturaDetalle;
import ec.edu.ups.principal.VistaPrincipal;
import static ec.edu.ups.vista.factura.DeleteFactura.x;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Byron PC
 */
public class ReadFactura extends javax.swing.JInternalFrame {
private ControladorFactura controladorFactura;
    private ResourceBundle mensajes;
    private Factura factura;
    public static String x;
    /**
     * Creates new form ReadFactura
     */
    public ReadFactura(ControladorFactura controladorFactura, ResourceBundle mensajes) {
        initComponents();
         x="x";
        int a=VistaPrincipal.desktopPane.getWidth()-this.getWidth();
        int b=VistaPrincipal.desktopPane.getHeight()-this.getHeight();
        setLocation(a/2,b/2);
        setVisible(true);
        this.controladorFactura = controladorFactura;
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }
 public void cambiarIdioma(ResourceBundle mensajes){
        
       jLabelcodigo.setText(mensajes.getString("factura.codigo"));
        jLabelnumeorfact.setText(mensajes.getString("factura.numero"));
        jLabelnombre.setText(mensajes.getString("factura.nombre"));
        jLabelcedula.setText(mensajes.getString("factura.cedula"));
        jLabeliva.setText(mensajes.getString("factura.iva"));
        jLabelsubtotal.setText(mensajes.getString("factura.subtotal"));
        jLabeltotal.setText(mensajes.getString("factura.total"));
        jLabeltelefono.setText(mensajes.getString("factura.telefono"));
        jLabeldirecion.setText(mensajes.getString("factura.direccion"));
        jLabelfecha.setText(mensajes.getString("factura.fecha"));
        btnbuscar.setText(mensajes.getString("boton.buscar"));
        btneliminar.setText(mensajes.getString("boton.eliminar"));
        
        JTableHeader tableHeader = tabadatos.getTableHeader();
        TableColumnModel tableColumnModel = tableHeader.getColumnModel();
        TableColumn tableColumn;
        tableColumn = tableColumnModel.getColumn(0);
        tableColumn.setHeaderValue(mensajes.getString("cliente.codigo"));
        tableColumn = tableColumnModel.getColumn(1);
        tableColumn.setHeaderValue(mensajes.getString("factura.cantidad"));
        tableColumn = tableColumnModel.getColumn(2);
        tableColumn.setHeaderValue(mensajes.getString("factura.producto"));
        tableColumn = tableColumnModel.getColumn(3);
        tableColumn.setHeaderValue(mensajes.getString("factura.precio"));
        tableHeader.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelnumeorfact = new javax.swing.JLabel();
        txtnumerofac = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelcedula = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        jLabelfecha = new javax.swing.JLabel();
        jLabeldirecion = new javax.swing.JLabel();
        jLabeltelefono = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        jLabelcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabadatos = new javax.swing.JTable();
        jLabelsubtotal = new javax.swing.JLabel();
        txtsubt = new javax.swing.JTextField();
        jLabeliva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabeltotal = new javax.swing.JLabel();
        txtto = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelnumeorfact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelnumeorfact.setText("Numero de Factura");

        btnbuscar.setText("Buscar");
        btnbuscar.setToolTipText("");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura a Eliminar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabelcedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcedula.setText("Cedula");

        jLabelnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelnombre.setText("Nombre");

        jLabelfecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelfecha.setText("Fecha");

        jLabeldirecion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeldirecion.setText("Direccion");

        jLabeltelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltelefono.setText("Telefono");

        txtcedula.setEditable(false);
        txtcedula.setEnabled(false);

        txtnombre.setEditable(false);
        txtnombre.setEnabled(false);

        txtdireccion.setEditable(false);
        txtdireccion.setEnabled(false);

        txttelefono.setEditable(false);
        txttelefono.setEnabled(false);

        txtfecha.setEditable(false);
        txtfecha.setEnabled(false);

        jLabelcodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcodigo.setText("Codigo");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);

        tabadatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabadatos);

        jLabelsubtotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelsubtotal.setText("Subtotal");

        jLabeliva.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeliva.setText("IVA 12%");

        jLabeltotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeltotal.setText("Total");

        btneliminar.setText("Cancelar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeliva)
                            .addComponent(jLabelsubtotal)
                            .addComponent(jLabeltotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsubt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelnombre)
                                        .addComponent(jLabeldirecion)
                                        .addComponent(jLabelcedula))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtcedula)
                                        .addComponent(txtnombre)
                                        .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                    .addGap(44, 44, 44)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelfecha)
                                        .addComponent(jLabelcodigo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtfecha)
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabeltelefono)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(btneliminar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcedula)
                    .addComponent(jLabelfecha)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelnombre)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelcodigo)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeldirecion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelsubtotal)
                    .addComponent(txtsubt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeliva)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltotal)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelnumeorfact)
                        .addGap(18, 18, 18)
                        .addComponent(txtnumerofac, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnbuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnumeorfact)
                    .addComponent(txtnumerofac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void vaciarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tabadatos.getModel();
        int filas=tabadatos.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
    }
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        vaciarTabla();
        int numero = Integer.parseInt(txtnumerofac.getText());
        factura = controladorFactura.read(numero);
        Cliente cliente = factura.getCliente();
        txtcedula.setText(cliente.getCedula());
        txtcodigo.setText(Integer.toString(cliente.getCodigo()));
        txtnombre.setText(cliente.getNombre());
        txtfecha.setText(factura.getFecha());
        txttelefono.setText(cliente.getTelefono());
        txtdireccion.setText(cliente.getDireccion());
        llenarDatos();
    }//GEN-LAST:event_btnbuscarActionPerformed
 public void llenarDatos(){
        
        DefaultTableModel modelo = (DefaultTableModel) tabadatos.getModel();
        List<FacturaDetalle> lista = factura.getDetalles();
        
        for(int i = 0; i < lista.size(); i++){
            Object[] datos = {lista.get(i).getProducto().getCodigoProducto(),
                lista.get(i).getCantidad(),
                lista.get(i).getProducto().getNombre(),
                lista.get(i).getPrecio(),
                lista.get(i).getSubtotal() };
            modelo.addRow(datos);
        }
        
        txtsubt.setText(Double.toString(factura.getSubtotal()));
        txtto.setText(Double.toString(factura.getTotal()));
        
    }
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        vaciarTabla();
        txtIva.setText("");
        txtcedula.setText("");
        txtcodigo.setText("");
        txtdireccion.setText("");
        txtfecha.setText("");
        txtnombre.setText("");
        txtnumerofac.setText("");
        txtsubt.setText("");
        txttelefono.setText("");
        txtto.setText("");
        JOptionPane.showMessageDialog(null, "Factura Eliminada");

    }//GEN-LAST:event_btneliminarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x=null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabelcedula;
    private javax.swing.JLabel jLabelcodigo;
    private javax.swing.JLabel jLabeldirecion;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JLabel jLabeliva;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabelnumeorfact;
    private javax.swing.JLabel jLabelsubtotal;
    private javax.swing.JLabel jLabeltelefono;
    private javax.swing.JLabel jLabeltotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabadatos;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumerofac;
    private javax.swing.JTextField txtsubt;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables
}
