/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.factura;

import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.controladores.ControladorFactura;
import ec.edu.ups.controladores.ControladorFacturaDetalle;
import ec.edu.ups.controladores.ControladorProducto;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Factura;
import ec.edu.ups.modelo.FacturaDetalle;
import ec.edu.ups.modelo.Producto;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Byron PC
 */
public class UpdateFactura extends javax.swing.JInternalFrame {
 private ControladorFactura controladorFactura;
    private ControladorCliente controladorCliente;
    private ControladorFacturaDetalle controladorFacturaDetalle;
    private ResourceBundle mensajes;
    private Factura factura;
    private Producto producto;
    private ControladorProducto controladorProducto;
    private int contador;
    private Cliente cliente;
    /**
     * Creates new form UpdateFactura
     */
    public UpdateFactura(ControladorCliente controladorCliente,ControladorFactura controladorFactura , ControladorFacturaDetalle controladorFacturaDetalle,ControladorProducto controladorProducto, ResourceBundle mensajes) {
        initComponents();
        factura = new Factura();
        cliente = new Cliente();
        this.controladorFactura = controladorFactura;
        this.controladorProducto = controladorProducto;
        this.controladorFacturaDetalle = controladorFacturaDetalle;
        this.controladorCliente = controladorCliente;
        contador = 0;
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }
public void cambiarIdioma(ResourceBundle mensajes){
        
        jLabelcodigo.setText(mensajes.getString("factura.codigo"));
        numeorfa.setText(mensajes.getString("factura.numero"));
       jLabelnombre.setText(mensajes.getString("factura.nombre"));
        jLabelcedula.setText(mensajes.getString("factura.cedula"));
        jLabeliva.setText(mensajes.getString("factura.iva"));
        jLabelsub.setText(mensajes.getString("factura.subtotal"));
       jLabelttoal.setText(mensajes.getString("factura.total"));
        jLabeltelefono1.setText(mensajes.getString("factura.telefono"));
        jLabeldireccion1.setText(mensajes.getString("factura.direccion"));
        jLabelfecha.setText(mensajes.getString("factura.fecha"));
        
        btnBuscar.setText(mensajes.getString("boton.buscar"));
        btnActualizar.setText(mensajes.getString("boton.actualizar"));
        
        JTableHeader tableHeader = tabladatos.getTableHeader();
        TableColumnModel tableColumnModel = tableHeader.getColumnModel();
        TableColumn tableColumn;
        tableColumn = tableColumnModel.getColumn(0);
        tableColumn.setHeaderValue(mensajes.getString("cliente.codigo"));
        tableColumn = tableColumnModel.getColumn(1);
        tableColumn.setHeaderValue(mensajes.getString("factura.cantidad"));
        tableColumn = tableColumnModel.getColumn(2);
        tableColumn.setHeaderValue(mensajes.getString("factura.producto"));
        tableColumn = tableColumnModel.getColumn(3);
        tableColumn.setHeaderValue(mensajes.getString("factura.precio"));
        tableHeader.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeldireccion = new javax.swing.JLabel();
        jLabeltelefono = new javax.swing.JLabel();
        txtdir = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSubtotal = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabelsub = new javax.swing.JLabel();
        jLabelfecha = new javax.swing.JLabel();
        jLabelcodigo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabeliva = new javax.swing.JLabel();
        jLabelttoal = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtnumeorfac = new javax.swing.JTextField();
        numeorfa = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jLabeldesc = new javax.swing.JLabel();
        txtIva1 = new javax.swing.JTextField();
        jLabeldireccion1 = new javax.swing.JLabel();
        jLabeltelefono1 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        txttelefon = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelcantidad = new javax.swing.JLabel();
        txtbusc = new javax.swing.JTextField();
        btnbuscarp = new javax.swing.JButton();
        jLabelcedula = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();

        jLabeldireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeldireccion.setText("Dirección");

        jLabeltelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabeltelefono.setText("Teléfono");

        txtdir.setEditable(false);

        txttele.setEditable(false);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Actualizar Factura");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura a Actualizar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 0, 153));

        txtSubtotal.setEditable(false);
        txtSubtotal.setEnabled(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        txtFecha.setEditable(false);
        txtFecha.setEnabled(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabelsub.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelsub.setText("Subtotal:");

        jLabelfecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelfecha.setText("Fecha:");

        jLabelcodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcodigo.setText("Codigo de Cliente:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabeliva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeliva.setText("Iva:");

        jLabelttoal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelttoal.setText("Total:");

        txtdesc.setEditable(false);
        txtdesc.setEnabled(false);

        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);

        numeorfa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        numeorfa.setText("Ingrese el numero de Factura:");

        jLabelnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelnombre.setText("Nombre:");

        txtcodigo.setEditable(false);
        txtcodigo.setEnabled(false);

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        jLabeldesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeldesc.setText("Descuento:");

        txtIva1.setEditable(false);
        txtIva1.setEnabled(false);

        jLabeldireccion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeldireccion1.setText("Dirección");

        jLabeltelefono1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeltelefono1.setText("Teléfono");

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");

        jLabelcantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcantidad.setText("Cantidad");

        btnbuscarp.setText("Agregar Cantidad");
        btnbuscarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarpActionPerformed(evt);
            }
        });

        jLabelcedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelcedula.setText("Cedula:");

        txtcedula.setEditable(false);
        txtcedula.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelcodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelttoal)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabelcantidad)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtbusc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(139, 139, 139))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGap(21, 21, 21)
                                                    .addComponent(btnbuscarp)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabelsub, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabeliva)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtIva1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabeldesc)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtnumeorfac, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(138, 138, 138)
                                            .addComponent(numeorfa)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabeltelefono1)
                                    .addGap(188, 188, 188)
                                    .addComponent(jLabelcedula)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtcedula)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabeldireccion1)
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txttelefon)
                                            .addComponent(txtdireccion)
                                            .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnActualizar)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(numeorfa)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnumeorfac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelfecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabeltelefono1)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeldireccion1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelcedula))))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcodigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelsub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeliva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeldesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelttoal))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelcantidad)
                            .addComponent(txtbusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscarp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        factura = new Factura();
        controladorFactura.update(factura);
        contador=0;
        llenarDatos();
        //Cliente cliente = controladorCliente.read(Integer.parseInt(txtCliente.getText()));
        limpiarTabla();
        txtnumeorfac.setEnabled(true);
        JOptionPane.showMessageDialog(null , "Factura Actualizada");
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        txtnumeorfac.setEnabled(true);
        limpiarTabla();
        int numerofact =Integer.parseInt(txtnumeorfac.getText());
        factura= controladorFactura.read(numerofact);
        txtcedula.setText(factura.getCliente().getCedula());
        cliente = factura.getCliente();
        txtcodigo.setText(Integer.toString(cliente.getCodigo()));
        txtnombre.setText(cliente.getNombre());
        txtFecha.setText(factura.getFecha());
        txttelefon.setText(cliente.getTelefono());
        txtdireccion.setText(cliente.getDireccion());
        llenarDatos();
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void btnbuscarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarpActionPerformed
        // TODO add your handling code here:
        FacturaDetalle facturadetalle = new FacturaDetalle();
        int codigopro= Integer.parseInt(txtbusc.getText());

        producto =controladorProducto.read(codigopro);
        facturadetalle.setProducto(producto);
        facturadetalle.setCantidad(Integer.parseInt(txtbusc.getText()));
        facturadetalle.setPrecio(producto.getPrecio());
        facturadetalle.setSubtotal(producto.getPrecio()*facturadetalle.getCantidad());
        
        factura.añadirFacturaDetalle(facturadetalle);
        llenarDatos();
    }//GEN-LAST:event_btnbuscarpActionPerformed
 public void llenarDatos(){
        
        DefaultTableModel modelo = (DefaultTableModel) tabladatos.getModel();
        List<FacturaDetalle> lista = factura.getDetalles();
        while(contador < lista.size()){
            Object[] datos = {factura.getDetalles().get(contador).getCodigo(),
                lista.get(contador).getCantidad(),
                lista.get(contador).getProducto().getNombre(),
                lista.get(contador).getPrecio(),
                lista.get(contador).getSubtotal() };
            modelo.addRow(datos);
            contador++;
        }
        calcularSubtotal();
        txtSubtotal.setText(Double.toString(factura.getSubtotal()));
        calcularTotal();
        txtTotal.setText(Double.toString(factura.getTotal()));
        
    }
  public void calcularSubtotal(){
        double suma = 0;
        for(int i = 0; i < factura.getDetalles().size(); i++){
            suma += factura.getDetalles().get(i).getSubtotal();
        }
        factura.setSubtotal(suma);
    }
    
    public void calcularTotal(){
        double total = factura.getSubtotal() + (factura.getSubtotal()*factura.getIva());
        factura.setTotal(total);
    }
    
    public void limpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tabladatos.getModel();
        int filas=tabladatos.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }
    }
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnbuscarp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelcantidad;
    private javax.swing.JLabel jLabelcedula;
    private javax.swing.JLabel jLabelcodigo;
    private javax.swing.JLabel jLabeldesc;
    private javax.swing.JLabel jLabeldireccion;
    private javax.swing.JLabel jLabeldireccion1;
    private javax.swing.JLabel jLabelfecha;
    private javax.swing.JLabel jLabeliva;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabelsub;
    private javax.swing.JLabel jLabeltelefono;
    private javax.swing.JLabel jLabeltelefono1;
    private javax.swing.JLabel jLabelttoal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeorfa;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva1;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbusc;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumeorfac;
    private javax.swing.JTextField txttele;
    private javax.swing.JTextField txttelefon;
    // End of variables declaration//GEN-END:variables
}
